#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'morganAndString' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING a
#  2. STRING b
#

def morganAndString(a, b):
    a+='z'
    b+='z'
    s=""
    n=len(a)
    m=len(b)
    while(n and m):
        if(a<b):
            s+=a[0]
            a=a[1:]
            n-=1
        else:
            s+=b[0]
            b=b[1:]
            m-=1
    if(n!=0):
        s+=a
    if(m!=0):
        s+=b
    return s[:-2]
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        a = input()

        b = input()

        result = morganAndString(a, b)

        fptr.write(result + '\n')

    fptr.close()
